# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespaceList:
- playground
- playground-test


deploymentList:
  myapp:
    namespace: playground
    containerName: myapp
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      imagePullSecrets: []
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"
    replicaCount: 2
    podAnnotations: {}
    podLabels: {}
    service:
      type: ClusterIP
      port: 80
  backend:
    namespace: playground
    containerName: backend
    image:
      repository: redis
      pullPolicy: IfNotPresent
      imagePullSecrets: []
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"
    replicaCount: 1
    podAnnotations: {}
    podLabels: {}
    service: {}

