{{- range $deployment, $definition := .Values.deploymentList}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment }}
  namespace: {{ $definition.namespace }}
spec:
  replicas: {{ $definition.replicaCount }}
  selector:
    matchLabels:
      app: {{ $deployment }}
  template:
    metadata:
      {{- with $definition.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $deployment }}
    spec:
      {{- with $definition.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $definition.containerName }}
          image: "{{ $definition.image.repository }}:{{ $definition.image.tag }}"
          imagePullPolicy: {{ $definition.image.pullPolicy }}
...
{{- end }}
