{{- range $deployment, $definition := .Values.deploymentList}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment }}
  namespace: {{ $definition.namespace }}
spec:
  replicas: {{ $definition.replicaCount }}
  selector:
    matchLabels:
      app: {{ $deployment }}
  template:
    metadata:
      {{- with $definition.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $deployment }}
    spec:
      {{- with $definition.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - image: busybox
        name: busybox
        command:
        - sh
        - -c
        - echo "<html><body><p>Welcome!!</p><p>$(hostname)</p></body></html>" > /data/index.html
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
        - name: {{ $definition.containerName }}
          image: "{{ $definition.image.repository }}:{{ $definition.image.tag }}"
          imagePullPolicy: {{ $definition.image.pullPolicy }}
          volumeMounts:
          - name: data
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: data
        emptyDir: {}
...
{{- end }}
